using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace EventApp.Models
{
    public class EventAppDbInitializer : DropCreateDatabaseAlways<EventAppDbContext>
    {
        protected override void Seed(EventAppDbContext context)
        {
            var types = new List<EventType>
            {
                new EventType { Type = "Concert" },
                new EventType { Type = "Festival" },
                new EventType { Type = "Sporting Event" },
                new EventType { Type = "Ceremony" },
                new EventType { Type = "Play" },
                new EventType { Type = "Convention" },
                new EventType { Type = "Media Event" },
                new EventType { Type = "Art Expo" },
                new EventType { Type = "Party" },
                new EventType { Type = "Mixer" }
            };

            var events = new List<Events>
            {
                new Events { Title = "The Rolling Stones", Description = "Rolling Stones in concert.", StartDate = "7/5/2019", StartTime = "7:00 PM", EndDate = "7/5/2019", EndTime = "11:00 PM", Location = "Megaplex", Type = types.Single(g => g.Type == "Concert"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 30000, AvailableTickets = 30000},
                new Events { Title = "Bruce Springsteen", Description = "Bruce Springsteen and the E Street Band.", StartDate = "8/5/2019", StartTime = "7:00 PM", EndDate = "8/5/2019", EndTime = "11:00 PM", Location = "Megaplex", Type = types.Single(g => g.Type == "Concert"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 30000, AvailableTickets = 30000},
                new Events { Title = "Metallica", Description = "Metallica in concert.", StartDate = "7/15/2019", StartTime = "7:00 PM", EndDate = "7/15/2019", EndTime = "11:00 PM", Location = "Megaplex", Type = types.Single(g => g.Type == "Concert"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 30000, AvailableTickets = 30000},
                new Events { Title = "Bonaroo", Description = "Bonaroo music festival.", StartDate = "7/18/2019", StartTime = "11:00 AM", EndDate = "7/18/2019", EndTime = "11:00 PM", Location = "Kruger Park", Type = types.Single(g => g.Type == "Festival"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 60000, AvailableTickets = 60000},
                new Events { Title = "Woodstock", Description = "Woodstock music festival.", StartDate = "7/20/2019", StartTime = "11:00 AM", EndDate = "7/20/2019", EndTime = "11:00 PM", Location = "Kruger Park", Type = types.Single(g => g.Type == "Festival"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 60000, AvailableTickets = 60000},
                new Events { Title = "Coachella", Description = "Coachella music festival.", StartDate = "7/26/2019", StartTime = "11:00 AM", EndDate = "7/28/2019", EndTime = "9:00 PM", Location = "Kruger Park", Type = types.Single(g => g.Type == "Festival"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 120000, AvailableTickets = 120000},
                new Events { Title = "All Star Game", Description = "Sports all star game.", StartDate = "6/20/2019", StartTime = "5:00 PM", EndDate = "6/20/2019", EndTime = "10:00 PM", Location = "Game Field", Type = types.Single(g => g.Type == "Sporting Event"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 40000, AvailableTickets = 40000},
                new Events { Title = "Race 500", Description = "500 lap championship race.", StartDate = "6/13/2019", StartTime = "12:00 PM", EndDate = "6/13/2019", EndTime = "11:00 PM", Location = "Motor Speedway", Type = types.Single(g => g.Type == "Sporting Event"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 80000, AvailableTickets = 80000},
                new Events { Title = "Pro Golf Open", Description = "Pro golf championship.", StartDate = "6/10/2019", StartTime = "8:00 AM", EndDate = "6/16/2019", EndTime = "9:00 PM", Location = "Golf Links", Type = types.Single(g => g.Type == "Sporting Event"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 100000, AvailableTickets = 100000},
                new Events { Title = "Movie Awards", Description = "Movie award ceremony.", StartDate = "9/20/2019", StartTime = "5:00 PM", EndDate = "9/20/2019", EndTime = "10:00 PM", Location = "Player's Theatre", Type = types.Single(g => g.Type == "Ceremony"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 2000, AvailableTickets = 2000},
                new Events { Title = "Music Awards", Description = "Music award ceremony.", StartDate = "8/15/2019", StartTime = "5:00 PM", EndDate = "8/15/2019", EndTime = "10:00 PM", Location = "Player's Theatre", Type = types.Single(g => g.Type == "Ceremony"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 1800, AvailableTickets = 1800},
                new Events { Title = "Sports Awards", Description = "Sprots award ceremony.", StartDate = "12/20/2019", StartTime = "5:00 PM", EndDate = "12/20/2019", EndTime = "10:00 PM", Location = "Player's Theatre", Type = types.Single(g => g.Type == "Ceremony"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 2000, AvailableTickets = 2000},
                new Events { Title = "Taming of the Shrew", Description = "Classic Shakespeare play.", StartDate = "10/22/2019", StartTime = "7:00 PM", EndDate = "10/22/2019", EndTime = "11:00 PM", Location = "Player's Theatre", Type = types.Single(g => g.Type == "Play"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 2500, AvailableTickets = 2500},
                new Events { Title = "A Streetcar Named Desire", Description = "Classic Tennessee Williams play.", StartDate = "10/29/2019", StartTime = "7:00 PM", EndDate = "10/29/2019", EndTime = "11:00 PM", Location = "Player's Theatre", Type = types.Single(g => g.Type == "Play"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 2500, AvailableTickets = 2500},
                new Events { Title = "The Marriage of Figaro", Description = "Classic Mozart opera.", StartDate = "10/29/2019", StartTime = "7:00 PM", EndDate = "10/29/2019", EndTime = "11:00 PM", Location = "Player's Theatre", Type = types.Single(g => g.Type == "Play"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 2500, AvailableTickets = 2500},
                new Events { Title = "Comics Con", Description = "Comic book convention.", StartDate ="7/5/2019", StartTime = "10:00 AM", EndDate = "7/7/2019", EndTime = "9:00 PM", Location = "Convention Center", Type = types.Single(g => g.Type == "Convention"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 40000, AvailableTickets = 40000},
                new Events { Title = "Car Convention", Description = "Car convention.", StartDate ="7/13/2019", StartTime = "11:00 AM", EndDate = "7/13/2019", EndTime = "9:00 PM", Location = "Convention Center", Type = types.Single(g => g.Type == "Convention"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 2000, AvailableTickets = 2000},
                new Events { Title = "Political Party Convention", Description = "National convention for political party.", StartDate ="6/25/2019", StartTime = "12:00 PM", EndDate = "6/27/2019", EndTime = "8:00 PM", Location = "Convention Center", Type = types.Single(g => g.Type == "Convention"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 20000, AvailableTickets = 20000},
                new Events { Title = "News Conference", Description = "Local news conference.", StartDate = "6/5/2019", StartTime = "12:00 PM", EndDate = "6/5/2019", EndTime = "9:00 PM", Location = "Civic Center", Type = types.Single(g => g.Type == "Media Event"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 1100, AvailableTickets = 1100},
                new Events { Title = "Athlete Photo Opportunity", Description = "Photo ops for major sports team.", StartDate = "6/18/2019", StartTime = "3:00 PM", EndDate = "6/18/2019", EndTime = "6:00 PM", Location = "Civic Center", Type = types.Single(g => g.Type == "Media Event"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 800, AvailableTickets = 800},
                new Events { Title = "Groundhog Day Ceremony", Description = "Groundhog Day annual ceremony.", StartDate = "2/2/2019", StartTime = "12:00 PM", EndDate = "2/2/2019", EndTime = "3:00 PM", Location = "Public Square", Type = types.Single(g => g.Type == "Media Event"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 11000, AvailableTickets = 60},
                new Events { Title = "Regional Art Exhibition", Description = "Large expo for art exhibits.", StartDate = "3/20/2019", StartTime = "12:00 PM", EndDate = "3/20/2019", EndTime = "10:00 PM", Location = "Convention Center", Type = types.Single(g => g.Type == "Art Expo"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 20000, AvailableTickets = 110},
                new Events { Title = "State-Wide Expo", Description = "Large expo for tech concepts.", StartDate = "6/20/2019", StartTime = "12:00 PM", EndDate = "6/20/2019", EndTime = "9:00 PM", Location = "Convention Center", Type = types.Single(g => g.Type == "Art Expo"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 20000, AvailableTickets = 20000},
                new Events { Title = "Museum of Art Expo", Description = "Museum of Art expo for historical exhibits.", StartDate = "6/30/2019", StartTime = "12:00 PM", EndDate = "6/30/2019", EndTime = "8:00 PM", Location = "Convention Center", Type = types.Single(g => g.Type == "Art Expo"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 20000, AvailableTickets = 20000},
                new Events { Title = "Foam Party", Description = "Dance party covered with foam.", StartDate = "4/20/2019", StartTime = "9:00 PM", EndDate = "4/21/2019", EndTime = "2:00 AM", Location = "Concert Venue", Type = types.Single(g => g.Type == "Party"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 250, AvailableTickets = 30},
                new Events { Title = "Brunch Party", Description = "Afternoon bunch and dinks.", StartDate = "4/20/2019", StartTime = "10:00 AM", EndDate = "4/20/2019", EndTime = "2:00 PM", Location = "Civoc Center", Type = types.Single(g => g.Type == "Party"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 200, AvailableTickets = 10},
                new Events { Title = "Fall Ball", Description = "Fall dance party.", StartDate = "10/20/2019", StartTime = "6:00 PM", EndDate = "10/20/2019", EndTime = "11:00 PM", Location = "Ballroom", Type = types.Single(g => g.Type == "Party"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 400, AvailableTickets = 400},
                new Events { Title = "Single's Mixer", Description = "Mixer for single men and women.", StartDate = "8/30/2019", StartTime = "6:00 PM", EndDate = "8/31/2019", EndTime = "1:00 AM", Location = "Local Bar", Type = types.Single(g => g.Type == "Mixer"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 100, AvailableTickets = 100},
                new Events { Title = "Busniess Marketing Mixer", Description = "Mixer for marketing.", StartDate = "5/3/2019", StartTime = "6:00 PM", EndDate = "5/3/2019", EndTime = "10:00 PM", Location = "Civic Center", Type = types.Single(g => g.Type == "Mixer"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 400, AvailableTickets = 0},
                new Events { Title = "Pet Mixer", Description = "Mixer for families seeking new pets.", StartDate = "7/24/2019", StartTime = "11:00 AM", EndDate = "7/24/2019", EndTime = "4:00 PM", Location = "Local Park", Type = types.Single(g => g.Type == "Mixer"), OrganizerName = "John Smith", OrganizerContact = "johnsmith@email.com", MaxTickets = 250, AvailableTickets = 250}
            };
        }
    }
}